string="deva""3456"'Megthink''67891'
number=234456 23459 6789.12 
boolean=True/False

////////////// 
Es5> Ecom Scropt 5
Es6 > Ecom scrpt 6
////Es5//////
var a = "HI"
var b =10
var c= True
typeof(a)
"string"
typeof(b)
"number"
typeof(c)
"undefined"
typeof(a)
"string"
typeof(b)
"number"
typeof(c)
"undefined"
var d ="3456"
undefined
typeof(d)
"string"
var f=5346.646
undefined
typeof (f)
"number"
var f ='333frged'
undefined
typeof(f)
"string"
////////basic operation/////
var a = 10
var b = 5
a+b
15
a-b
5
a*b
50
a/b
2
a%b
2%4
3%4
4%4

1,1,1
100%101

////////string//////
var a = "Hi"
var b = "JavaScript"

undefined
a+b(Concat)
"HiJavaScript"
a-b
NaN (Not a number)
a*b
NaN
a/b
NaN
a%b
NaN


var a = "Hi"
var b = "JavaScript"

undefined
a+b
"HiJavaScript"
a-b
NaN
a*b
NaN
a/b
NaN
a%b
NaN

c+a
"10Hi"
    
sting+string= string
string+number=string
number+string=string
number+number=number



10+"20"+30
"1020"+30
"102030"
"10"+20+30
"1020"+30
"102030"


10+20+"30"
30+"30"
"3030"


10+"20"+30-1
102029
"10"+20+30-1
102029
10+20+"30"-1
3029






